[build]
command = "mkdir -p netlify/functions/templates && cp -r templates/* netlify/functions/templates/"
functions = "netlify/functions"
publish = "public"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200
force = true 